// Placeholder. Generated by `pnpm --filter @hybrid/db db:gen` (kysely-codegen
// introspecting DIRECT_URL). Committed output is diff-checked in CI.
// This stub keeps `export type * from "./types"` resolvable before first gen.
export {};
