/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuditAction = "dbid.review_approve" | "dbid.review_reject" | "member.invite" | "member.remove" | "member.role_change" | "order.cancel" | "order.refund" | "payment_account.update" | "platform_admin.login" | "product.create" | "product.delete" | "product.update" | "settings.update" | "tenant.plan_change" | "tenant.reactivate" | "tenant.suspend";

export type BillingProvider = "bkash" | "manual" | "nagad";

export type CodStatus = "collected" | "discrepancy" | "pending" | "reconciled" | "remitted";

export type CourierProvider = "manual" | "paperfly" | "pathao" | "redx" | "steadfast";

export type CustomerType = "distributor" | "end_consumer" | "retailer" | "wholesaler";

export type DiscountStatus = "active" | "disabled" | "expired" | "scheduled";

export type DiscountType = "fixed_amount" | "free_shipping" | "percentage";

export type DomainType = "custom" | "subdomain";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InvoiceStatus = "draft" | "open" | "overdue" | "paid" | "void";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LandingPageStatus = "archived" | "draft" | "published";

export type MemberRole = "admin" | "owner" | "staff";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderFulfillmentStatus = "cancelled" | "confirmed" | "delivered" | "in_transit" | "packed" | "pending" | "returned" | "shipped";

export type OrderMode = "retail" | "wholesale";

export type OrderPaymentStatus = "paid" | "partially_paid" | "partially_refunded" | "refunded" | "unpaid";

export type OrderSource = "api" | "landing_page" | "manual" | "messenger" | "storefront";

export type PageStatus = "draft" | "published";

export type PaymentProvider = "bkash" | "cod" | "hybridpay" | "manual" | "nagad" | "sslcommerz";

export type PaymentStatus = "cancelled" | "failed" | "pending" | "refunded" | "success";

export type PlatformRole = "accountant" | "ops" | "sales" | "super_admin" | "support";

export type ProductStatus = "active" | "archived" | "draft";

export type RefundMethod = "bkash" | "cash" | "nagad" | "none";

export type ReturnReason = "customer_refused" | "damaged" | "fake_order" | "not_as_described" | "other" | "rto_undelivered" | "size_issue" | "wrong_item";

export type ReturnStatus = "approved" | "cancelled" | "completed" | "in_transit" | "received" | "refunded" | "rejected" | "requested";

export type ReturnType = "exchange" | "return" | "rto";

export type ShipmentStatus = "cancelled" | "created" | "delivered" | "hold" | "in_transit" | "picked_up" | "returned";

export type SslStatus = "failed" | "issued" | "none" | "pending";

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "past_due" | "trialing";

export type TenantBusinessType = "both" | "retail" | "wholesale";

export type TenantStatus = "active" | "cancelled" | "past_due" | "suspended" | "trial";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AnalyticsEvent {
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  id: Generated<Int8>;
  occurredAt: Generated<Timestamp>;
  payload: Generated<Json>;
  sessionId: string | null;
  tenantId: string;
  type: string;
}

export interface AppUser {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  fullName: string | null;
  id: Generated<string>;
  isPlatformAdmin: Generated<boolean>;
  passwordHash: string | null;
  phone: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface AuditLog {
  action: AuditAction;
  actorUserId: string | null;
  details: Generated<Json>;
  id: Generated<string>;
  ipAddress: string | null;
  occurredAt: Generated<Timestamp>;
  resourceId: string | null;
  resourceType: string | null;
  tenantId: string | null;
  userAgent: string | null;
}

export interface Campaign {
  audience: Generated<string>;
  channel: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  message: string;
  recipientCount: Generated<number>;
  sentAt: Timestamp | null;
  sentCount: Generated<number>;
  status: Generated<string>;
  tenantId: string;
}

export interface Cart {
  abandonedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  email: string | null;
  id: Generated<string>;
  items: Json;
  phone: string | null;
  recoveredAt: Timestamp | null;
  recoveryToken: Generated<string | null>;
  tenantId: string;
  total: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
}

export interface CartReminder {
  cartId: string;
  channel: string;
  id: Generated<string>;
  sentAt: Generated<Timestamp>;
  status: Generated<string>;
  templateKey: string;
  tenantId: string;
}

export interface CodRemittance {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  payload: Generated<Json>;
  processedAt: Timestamp | null;
  provider: CourierProvider;
  reference: string | null;
  remittedAt: Timestamp | null;
  status: Generated<string>;
  tenantId: string;
  totalAmount: Generated<Numeric>;
  unmatchedCount: Generated<number>;
}

export interface Collection {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  imageUrl: string | null;
  isActive: Generated<boolean>;
  slug: string;
  sortOrder: Generated<number>;
  tenantId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CourierAccount {
  createdAt: Generated<Timestamp>;
  credentials: Generated<Json>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  provider: CourierProvider;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Customer {
  binNo: string | null;
  businessName: string | null;
  createdAt: Generated<Timestamp>;
  creditLimit: Generated<Numeric>;
  currentDue: Generated<Numeric>;
  customerType: Generated<CustomerType>;
  email: string | null;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  name: string | null;
  note: string | null;
  ordersCount: Generated<number>;
  phone: string | null;
  tags: Generated<string[]>;
  tenantId: string;
  totalSpent: Generated<Numeric>;
  tradeLicenseNo: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface CustomerAddress {
  addressLine: string | null;
  createdAt: Generated<Timestamp>;
  customerId: string;
  district: string | null;
  division: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  phone: string | null;
  recipientName: string | null;
  tenantId: string;
  thana: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface CustomerLedger {
  amount: Numeric;
  balance: Numeric;
  createdAt: Generated<Timestamp>;
  customerId: string;
  id: Generated<string>;
  note: string | null;
  referenceId: string | null;
  referenceType: string | null;
  tenantId: string;
  type: string;
}

export interface DbidSubmission {
  binSealed: Json | null;
  businessName: string | null;
  businessType: string | null;
  createdAt: Generated<Timestamp>;
  dbidNumber: string | null;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  nidSealed: Json | null;
  ownerDob: Timestamp | null;
  ownerFullName: string | null;
  reviewedAt: Timestamp | null;
  reviewerNotes: string | null;
  status: Generated<string>;
  step: Generated<number>;
  submittedAt: Timestamp | null;
  tenantId: string;
  tinSealed: Json | null;
  tradeLicenseSealed: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface Discount {
  appliesTo: Generated<Json>;
  code: string;
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp | null;
  id: Generated<string>;
  minSubtotal: Generated<Numeric>;
  perCustomerLimit: number | null;
  startsAt: Timestamp | null;
  status: Generated<DiscountStatus>;
  tenantId: string;
  title: string | null;
  type: DiscountType;
  updatedAt: Generated<Timestamp>;
  usageLimit: number | null;
  usedCount: Generated<number>;
  value: Generated<Numeric>;
}

export interface Invoice {
  amount: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  dueAt: Timestamp | null;
  id: Generated<string>;
  invoiceNumber: string | null;
  paidAt: Timestamp | null;
  provider: BillingProvider | null;
  providerRef: string | null;
  status: Generated<InvoiceStatus>;
  subscriptionId: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface LandingPage {
  blocks: Generated<Json>;
  createdAt: Generated<Timestamp>;
  domainId: string | null;
  funnelConfig: Generated<Json>;
  id: Generated<string>;
  publishedAt: Timestamp | null;
  slug: string;
  status: Generated<LandingPageStatus>;
  tenantId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface LoyaltyLedger {
  createdAt: Generated<Timestamp>;
  customerId: string;
  id: Generated<string>;
  orderId: string | null;
  points: number;
  reason: Generated<string>;
  tenantId: string;
}

export interface LoyaltyProgram {
  earnPer100: Generated<number>;
  enabled: Generated<boolean>;
  takaPerPoint: Generated<Numeric>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface MarketplaceCategory {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  nameBn: string;
  nameEn: string;
  slug: string;
  sortOrder: Generated<number>;
}

export interface MarketplaceCommission {
  commissionAmount: Numeric;
  createdAt: Generated<Timestamp>;
  gross: Numeric;
  id: Generated<string>;
  marketplaceOrderId: string | null;
  rate: Numeric;
  suborderId: string | null;
  tenantId: string;
}

export interface MarketplaceConfig {
  commissionRate: Generated<Numeric>;
  id: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface MarketplaceCustomer {
  binNo: string | null;
  businessName: string | null;
  createdAt: Generated<Timestamp>;
  customerType: Generated<string>;
  email: string | null;
  id: Generated<string>;
  isVerified: Generated<boolean>;
  name: string | null;
  passwordHash: string | null;
  phone: string;
  tradeLicenseNo: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface MarketplaceListing {
  categoryId: string | null;
  description: string | null;
  hidden: Generated<boolean>;
  id: Generated<string>;
  imageUrl: string | null;
  inStock: Generated<boolean>;
  isWholesale: Generated<boolean>;
  moq: number | null;
  priceFrom: Generated<Numeric>;
  productId: string;
  ratingAvg: Generated<Numeric>;
  ratingCount: Generated<number>;
  searchTsv: Generated<string | null>;
  slug: string;
  status: Generated<string>;
  syncedAt: Generated<Timestamp>;
  tenantId: string;
  title: string;
  vendorName: string;
  vendorSlug: string;
  wholesaleOnly: Generated<boolean>;
}

export interface MarketplaceListingVariant {
  id: string;
  inStock: Generated<boolean>;
  listingId: string;
  moq: number | null;
  options: Generated<Json>;
  position: Generated<number>;
  price: Generated<Numeric>;
  productId: string;
  tenantId: string;
  tierPrices: Generated<Json>;
  title: string | null;
  wholesalePrice: Numeric | null;
}

export interface MarketplaceOrder {
  buyerId: string;
  contactName: string;
  contactPhone: string;
  createdAt: Generated<Timestamp>;
  grandTotal: Generated<Numeric>;
  id: Generated<string>;
  idempotencyKey: string | null;
  itemsTotal: Generated<Numeric>;
  shipDistrict: string;
  shipDivision: string;
  shipLine: string;
  shippingTotal: Generated<Numeric>;
  shipThana: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  vendorCount: Generated<number>;
}

export interface MarketplaceReview {
  body: string | null;
  buyerId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  moderatedAt: Timestamp | null;
  productId: string;
  rating: number;
  status: Generated<string>;
  tenantId: string;
  verifiedPurchase: Generated<boolean>;
}

export interface MarketplaceSession {
  buyerId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ip: string | null;
  revokedAt: Timestamp | null;
  tokenHash: string;
  userAgent: string | null;
}

export interface MarketplaceSuborder {
  buyerId: string;
  codAmount: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  grandTotal: Generated<Numeric>;
  id: Generated<string>;
  itemsSubtotal: Generated<Numeric>;
  marketplaceOrderId: string;
  orderId: string | null;
  orderNumber: Int8 | null;
  paymentStatus: Generated<string>;
  shippingTotal: Generated<Numeric>;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  vendorName: string;
}

export interface NavigationMenu {
  createdAt: Generated<Timestamp>;
  handle: string;
  id: Generated<string>;
  items: Generated<Json>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface OrderCounter {
  nextValue: Generated<Int8>;
  tenantId: string;
}

export interface OrderItem {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  lineTotal: Generated<Numeric>;
  orderId: string;
  productId: string | null;
  quantity: Generated<number>;
  sku: string | null;
  tenantId: string;
  title: string;
  unitPrice: Generated<Numeric>;
  variantId: string | null;
  variantTitle: string | null;
}

export interface OrderNote {
  authorId: string | null;
  body: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  orderId: string;
  tenantId: string;
}

export interface Orders {
  assignedAt: Timestamp | null;
  assigneeId: string | null;
  billingAddress: Generated<Json>;
  cancelledAt: Timestamp | null;
  channel: Generated<string>;
  codAmount: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  creditApproved: Generated<boolean>;
  creditDue: Generated<Numeric>;
  creditTerms: Generated<Json>;
  currency: Generated<string>;
  customerEmail: string | null;
  customerId: string | null;
  customerName: string | null;
  customerPhone: string | null;
  discountCode: string | null;
  discountTotal: Generated<Numeric>;
  fulfillmentStatus: Generated<OrderFulfillmentStatus>;
  grandTotal: Generated<Numeric>;
  id: Generated<string>;
  isPurchaseOrder: Generated<boolean>;
  marketplaceOrderId: string | null;
  note: string | null;
  orderMode: Generated<OrderMode>;
  orderNumber: Int8 | null;
  paymentStatus: Generated<OrderPaymentStatus>;
  placedAt: Generated<Timestamp>;
  poReference: string | null;
  shippingAddress: Generated<Json>;
  shippingTotal: Generated<Numeric>;
  source: Generated<OrderSource>;
  subtotal: Generated<Numeric>;
  taxTotal: Generated<Numeric>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface OtpCode {
  attempts: Generated<number>;
  codeHash: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  purpose: string;
  target: string;
  used: Generated<boolean>;
  userId: string | null;
}

export interface Payment {
  amount: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  orderId: string;
  paidAt: Timestamp | null;
  payload: Generated<Json>;
  provider: PaymentProvider;
  providerRef: string | null;
  status: Generated<PaymentStatus>;
  tenantId: string;
  transactionId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PaymentAccount {
  createdAt: Generated<Timestamp>;
  credentials: Generated<Json>;
  id: Generated<string>;
  isEnabled: Generated<boolean>;
  provider: PaymentProvider;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface PgStatStatements {
  blkReadTime: number | null;
  blkWriteTime: number | null;
  calls: Int8 | null;
  dbid: number | null;
  jitEmissionCount: Int8 | null;
  jitEmissionTime: number | null;
  jitFunctions: Int8 | null;
  jitGenerationTime: number | null;
  jitInliningCount: Int8 | null;
  jitInliningTime: number | null;
  jitOptimizationCount: Int8 | null;
  jitOptimizationTime: number | null;
  localBlksDirtied: Int8 | null;
  localBlksHit: Int8 | null;
  localBlksRead: Int8 | null;
  localBlksWritten: Int8 | null;
  maxExecTime: number | null;
  maxPlanTime: number | null;
  meanExecTime: number | null;
  meanPlanTime: number | null;
  minExecTime: number | null;
  minPlanTime: number | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  sharedBlksDirtied: Int8 | null;
  sharedBlksHit: Int8 | null;
  sharedBlksRead: Int8 | null;
  sharedBlksWritten: Int8 | null;
  stddevExecTime: number | null;
  stddevPlanTime: number | null;
  tempBlkReadTime: number | null;
  tempBlksRead: Int8 | null;
  tempBlksWritten: Int8 | null;
  tempBlkWriteTime: number | null;
  toplevel: boolean | null;
  totalExecTime: number | null;
  totalPlanTime: number | null;
  userid: number | null;
  walBytes: Numeric | null;
  walFpi: Int8 | null;
  walRecords: Int8 | null;
}

export interface PgStatStatementsInfo {
  dealloc: Int8 | null;
  statsReset: Timestamp | null;
}

export interface PhoneBlocklist {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  phone: string;
  reason: string | null;
  tenantId: string;
}

export interface Plan {
  billingInterval: Generated<string>;
  code: string;
  createdAt: Generated<Timestamp>;
  features: Generated<Json>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  maxCustomDomains: Generated<number>;
  maxOrdersMonth: number | null;
  maxProducts: number | null;
  maxStaff: Generated<number>;
  name: string;
  priceBdt: Generated<Numeric>;
  sortOrder: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface PlatformExpense {
  amount: Numeric;
  category: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  incurredOn: Generated<Timestamp>;
  note: string | null;
  vendor: string | null;
}

export interface PlatformMember {
  createdAt: Generated<Timestamp>;
  role: Generated<PlatformRole>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Product {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  isWholesale: Generated<boolean>;
  marketplaceHidden: Generated<boolean>;
  moq: number | null;
  options: Generated<Json>;
  productType: string | null;
  seo: Generated<Json>;
  slug: string;
  status: Generated<ProductStatus>;
  tags: Generated<string[]>;
  tenantId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  vendor: string | null;
  wholesaleOnly: Generated<boolean>;
}

export interface ProductCollection {
  collectionId: string;
  position: Generated<number>;
  productId: string;
  tenantId: string;
}

export interface ProductImage {
  alt: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  position: Generated<number>;
  productId: string;
  tenantId: string;
  url: string;
}

export interface ProductReview {
  body: string | null;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  customerName: string | null;
  id: Generated<string>;
  moderatedAt: Timestamp | null;
  orderId: string | null;
  productId: string;
  rating: number;
  status: Generated<string>;
  tenantId: string;
}

export interface ProductVariant {
  barcode: string | null;
  compareAtPrice: Numeric | null;
  costPrice: Numeric | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  inventoryQuantity: Generated<number>;
  isActive: Generated<boolean>;
  moq: number | null;
  options: Generated<Json>;
  position: Generated<number>;
  price: Generated<Numeric>;
  productId: string;
  sku: string | null;
  tenantId: string;
  tierPrices: Generated<Json>;
  title: string | null;
  trackInventory: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  weightGrams: number | null;
  wholesalePrice: Numeric | null;
}

export interface PurchaseRequest {
  buyerCustomerId: string;
  convertedOrderId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  items: Generated<Json>;
  quotedSubtotal: Numeric | null;
  quotedTotal: Numeric | null;
  status: Generated<string>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ReturnItem {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  orderItemId: string | null;
  quantity: Generated<number>;
  restock: Generated<boolean>;
  returnId: string;
  tenantId: string;
  title: string | null;
  variantId: string | null;
}

export interface ReturnRequest {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  note: string | null;
  orderId: string;
  reason: Generated<ReturnReason>;
  refundAmount: Generated<Numeric>;
  refundedAt: Timestamp | null;
  refundMethod: Generated<RefundMethod>;
  resolvedAt: Timestamp | null;
  restocked: Generated<boolean>;
  reverseShipmentId: string | null;
  status: Generated<ReturnStatus>;
  tenantId: string;
  type: Generated<ReturnType>;
  updatedAt: Generated<Timestamp>;
}

export interface Shipment {
  codAmount: Generated<Numeric>;
  codCollected: Numeric | null;
  codRemitted: Numeric | null;
  codStatus: Generated<CodStatus>;
  consignmentId: string | null;
  createdAt: Generated<Timestamp>;
  deliveredAt: Timestamp | null;
  discrepancyAmount: Generated<Numeric>;
  id: Generated<string>;
  orderId: string;
  payload: Generated<Json>;
  provider: CourierProvider;
  rawStatus: string | null;
  reconciled: Generated<boolean>;
  remittanceId: string | null;
  status: Generated<ShipmentStatus>;
  tenantId: string;
  trackingCode: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ShippingConfig {
  defaultRate: Generated<Numeric>;
  enabled: Generated<boolean>;
  freeAbove: Numeric | null;
  originDistrict: string | null;
  originDivision: string | null;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  volumetricDivisor: Generated<number>;
}

export interface ShippingZoneRate {
  base: Generated<Numeric>;
  id: Generated<string>;
  perKg: Generated<Numeric>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
  zone: string;
}

export interface StorePage {
  blocks: Generated<Json>;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  seo: Generated<Json>;
  slug: string;
  status: Generated<PageStatus>;
  tenantId: string;
  title: string | null;
  type: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Subscription {
  billingProvider: BillingProvider | null;
  cancelAtPeriodEnd: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp | null;
  currentPeriodStart: Timestamp | null;
  id: Generated<string>;
  planId: string;
  providerRef: string | null;
  status: Generated<SubscriptionStatus>;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Tenant {
  businessType: Generated<TenantBusinessType>;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  defaultLocale: Generated<string>;
  id: Generated<string>;
  kycDocuments: Generated<Json>;
  kycStatus: Generated<string>;
  name: string;
  ownerUserId: string | null;
  planId: string | null;
  settings: Generated<Json>;
  slug: string;
  status: Generated<TenantStatus>;
  suspendedAt: Timestamp | null;
  timezone: Generated<string>;
  trialEndsAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  wholesaleApproved: Generated<boolean>;
}

export interface TenantAssignment {
  assignedAt: Generated<Timestamp>;
  tenantId: string;
  userId: string;
}

export interface TenantDomain {
  createdAt: Generated<Timestamp>;
  domain: string;
  id: Generated<string>;
  isPrimary: Generated<boolean>;
  sslStatus: Generated<SslStatus>;
  tenantId: string;
  type: DomainType;
  updatedAt: Generated<Timestamp>;
  verificationToken: string | null;
  verified: Generated<boolean>;
  verifiedAt: Timestamp | null;
}

export interface TenantMember {
  acceptedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  invitedAt: Timestamp | null;
  role: Generated<MemberRole>;
  tenantId: string;
  userId: string;
}

export interface TenantThemeSettings {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  settings: Generated<Json>;
  tenantId: string;
  themeId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Theme {
  category: string | null;
  code: string;
  createdAt: Generated<Timestamp>;
  defaultSettings: Generated<Json>;
  description: string | null;
  id: Generated<string>;
  isActive: Generated<boolean>;
  name: string;
  previewImageUrl: string | null;
  sectionsSchema: Generated<Json>;
  sortOrder: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface TrackingEventLog {
  errorMessage: string | null;
  eventId: string;
  eventName: string;
  eventSource: string;
  id: Generated<string>;
  occurredAt: Generated<Timestamp>;
  payload: Json | null;
  platform: string;
  responseBody: string | null;
  responseCode: number | null;
  status: string;
  tenantId: string;
}

export interface UsageCounter {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  ordersCount: Generated<number>;
  periodMonth: Timestamp;
  tenantId: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ip: string | null;
  revokedAt: Timestamp | null;
  tokenHash: string;
  userAgent: string | null;
  userId: string;
}

export interface WebhookEvent {
  eventType: string | null;
  externalId: string | null;
  id: Generated<string>;
  payload: Generated<Json>;
  processed: Generated<boolean>;
  processedAt: Timestamp | null;
  provider: string;
  receivedAt: Generated<Timestamp>;
  tenantId: string | null;
}

export interface DB {
  analyticsEvent: AnalyticsEvent;
  appUser: AppUser;
  auditLog: AuditLog;
  campaign: Campaign;
  cart: Cart;
  cartReminder: CartReminder;
  codRemittance: CodRemittance;
  collection: Collection;
  courierAccount: CourierAccount;
  customer: Customer;
  customerAddress: CustomerAddress;
  customerLedger: CustomerLedger;
  dbidSubmission: DbidSubmission;
  discount: Discount;
  invoice: Invoice;
  landingPage: LandingPage;
  loyaltyLedger: LoyaltyLedger;
  loyaltyProgram: LoyaltyProgram;
  marketplaceCategory: MarketplaceCategory;
  marketplaceCommission: MarketplaceCommission;
  marketplaceConfig: MarketplaceConfig;
  marketplaceCustomer: MarketplaceCustomer;
  marketplaceListing: MarketplaceListing;
  marketplaceListingVariant: MarketplaceListingVariant;
  marketplaceOrder: MarketplaceOrder;
  marketplaceReview: MarketplaceReview;
  marketplaceSession: MarketplaceSession;
  marketplaceSuborder: MarketplaceSuborder;
  navigationMenu: NavigationMenu;
  orderCounter: OrderCounter;
  orderItem: OrderItem;
  orderNote: OrderNote;
  orders: Orders;
  otpCode: OtpCode;
  payment: Payment;
  paymentAccount: PaymentAccount;
  pgStatStatements: PgStatStatements;
  pgStatStatementsInfo: PgStatStatementsInfo;
  phoneBlocklist: PhoneBlocklist;
  plan: Plan;
  platformExpense: PlatformExpense;
  platformMember: PlatformMember;
  product: Product;
  productCollection: ProductCollection;
  productImage: ProductImage;
  productReview: ProductReview;
  productVariant: ProductVariant;
  purchaseRequest: PurchaseRequest;
  returnItem: ReturnItem;
  returnRequest: ReturnRequest;
  shipment: Shipment;
  shippingConfig: ShippingConfig;
  shippingZoneRate: ShippingZoneRate;
  storePage: StorePage;
  subscription: Subscription;
  tenant: Tenant;
  tenantAssignment: TenantAssignment;
  tenantDomain: TenantDomain;
  tenantMember: TenantMember;
  tenantThemeSettings: TenantThemeSettings;
  theme: Theme;
  trackingEventLog: TrackingEventLog;
  usageCounter: UsageCounter;
  userSession: UserSession;
  webhookEvent: WebhookEvent;
}
